server:
  port: 7001
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #不将自己注册进eureka
    #表示不从eureka注册中心抓取已有的注册信息，默认为true，单节点无所谓
    #集群必须为true才能配合ribbon使用负载均衡
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/